import { Agent } from "@/types";

export const agentDashboardData: Agent[] = [
  {
    recordId: "agt-001",
    name: "Mariz",
    surname: "CABIDO",
    email: "mariz@sifao.com",
    brand: "SVG",
    hot_leads_today: 7,
    today_calls_made: 31,
    winner: true,
    monthly_calls: 326,
    monthly_hot_leads: 38,
    monthly_lost_hot_leads: 6,
    monthly_contract_closed: 8,
    monthly_points: 182,
    last_month_calls: 292,
    last_month_hot_lead: 24,
    last_month_contract_closed: 6,
    last_month_winner: false,
    last_month_points: 139,
    monthly_winner: true,
    last_month_lost_lead: 9,
    count_wins: 6,
    all_points: 801,
  },
  {
    recordId: "agt-002",
    name: "Tom",
    surname: "Silver",
    email: "tom@sifao.com",
    brand: "95RM",
    hot_leads_today: 5,
    today_calls_made: 27,
    winner: false,
    monthly_calls: 289,
    monthly_hot_leads: 29,
    monthly_lost_hot_leads: 7,
    monthly_contract_closed: 7,
    monthly_points: 156,
    last_month_calls: 271,
    last_month_hot_lead: 23,
    last_month_contract_closed: 5,
    last_month_winner: true,
    last_month_points: 147,
    monthly_winner: false,
    last_month_lost_lead: 8,
    count_wins: 4,
    all_points: 728,
  },
  {
    recordId: "agt-003",
    name: "Chris",
    surname: "Moore",
    email: "chris@sifao.com",
    brand: "Benton",
    hot_leads_today: 4,
    today_calls_made: 22,
    winner: false,
    monthly_calls: 258,
    monthly_hot_leads: 24,
    monthly_lost_hot_leads: 6,
    monthly_contract_closed: 5,
    monthly_points: 129,
    last_month_calls: 238,
    last_month_hot_lead: 17,
    last_month_contract_closed: 4,
    last_month_winner: false,
    last_month_points: 111,
    monthly_winner: false,
    last_month_lost_lead: 7,
    count_wins: 3,
    all_points: 564,
  },
  {
    recordId: "agt-004",
    name: "Bryan",
    surname: "Taylor",
    email: "bryan@sifao.com",
    brand: "95RM",
    hot_leads_today: 6,
    today_calls_made: 29,
    winner: false,
    monthly_calls: 301,
    monthly_hot_leads: 31,
    monthly_lost_hot_leads: 9,
    monthly_contract_closed: 6,
    monthly_points: 161,
    last_month_calls: 272,
    last_month_hot_lead: 21,
    last_month_contract_closed: 4,
    last_month_winner: false,
    last_month_points: 126,
    monthly_winner: false,
    last_month_lost_lead: 10,
    count_wins: 4,
    all_points: 689,
  },
];
