import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../public/css/globals.css";
import QueryProvider from "@/providers/QueryProvider";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/providers/AuthProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { DrawerProvider } from "@/providers/DrawerProvider";
import { RoutePreloader } from "@/components/ui";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        suppressHydrationWarning
        className="min-h-full flex flex-col bg-background text-foreground font-sans transition-colors duration-300"
      >
        <ThemeProvider>
          <QueryProvider>
            <AuthProvider>
              <DrawerProvider>
                <RoutePreloader />
                {children}
              </DrawerProvider>
              <ToastContainer
                position="top-right"
                autoClose={3000}
                newestOnTop
                closeOnClick
                pauseOnHover
                theme="colored"
              />
            </AuthProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
